CREATE TABLE wod_level (id INT PRIMARY KEY, name VARCHAR(30) NOT NULL);
INSERT INTO wod_level VALUES (1,'Beginner'),(2,'Initiated'),(3,'Intermediate'),(4,'Confirmed'),(5,'Advanced'),(6,'Mad Man');
ALTER TABLE athletes ADD COLUMN wod_level_id INT NOT NULL DEFAULT 1 REFERENCES wod_level(id);
CREATE TABLE movement_pattern (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE movement_type (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE exercise_category (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE equipment (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE exercise_family (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE muscle_group (id VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE wod_exercise (id VARCHAR(60) PRIMARY KEY, name VARCHAR(100) NOT NULL, family_id VARCHAR(40) NOT NULL REFERENCES exercise_family(id), category_id VARCHAR(40) NOT NULL REFERENCES exercise_category(id), movement_type_id VARCHAR(40) NOT NULL REFERENCES movement_type(id), difficulty INT NOT NULL CHECK(difficulty BETWEEN 1 AND 6), unit VARCHAR(12) NOT NULL CHECK(unit IN ('reps','seconds','meters','calories')), seconds_per_unit DOUBLE PRECISION NOT NULL, note VARCHAR(500) NOT NULL);
CREATE TABLE exercise_pattern (exercise_id VARCHAR(60) REFERENCES wod_exercise(id), pattern_id VARCHAR(40) REFERENCES movement_pattern(id), PRIMARY KEY(exercise_id,pattern_id));
CREATE TABLE exercise_equipment (exercise_id VARCHAR(60) REFERENCES wod_exercise(id), equipment_id VARCHAR(40) REFERENCES equipment(id), PRIMARY KEY(exercise_id,equipment_id));
CREATE TABLE exercise_muscle (exercise_id VARCHAR(60) REFERENCES wod_exercise(id), muscle_id VARCHAR(40) REFERENCES muscle_group(id), PRIMARY KEY(exercise_id,muscle_id));
CREATE TABLE exercise_level_config (exercise_id VARCHAR(60) REFERENCES wod_exercise(id), level_id INT REFERENCES wod_level(id), suggested_reps INT NOT NULL, suggested_weight DOUBLE PRECISION NOT NULL, PRIMARY KEY(exercise_id,level_id));
CREATE TABLE wod_type (id VARCHAR(20) PRIMARY KEY, name VARCHAR(40) NOT NULL);
CREATE TABLE wod_stimulus (id VARCHAR(30) PRIMARY KEY, name VARCHAR(60) NOT NULL);
CREATE TABLE wod_template (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100) NOT NULL, stimulus_id VARCHAR(30) NOT NULL REFERENCES wod_stimulus(id), type_id VARCHAR(20) NOT NULL REFERENCES wod_type(id), min_exercises INT NOT NULL, max_exercises INT NOT NULL, target_duration INT NOT NULL);
CREATE TABLE user_wod_preference (user_id UUID PRIMARY KEY REFERENCES athletes(id) ON DELETE CASCADE);
CREATE TABLE user_equipment_preference (user_id UUID REFERENCES athletes(id) ON DELETE CASCADE, equipment_id VARCHAR(40) REFERENCES equipment(id), PRIMARY KEY(user_id,equipment_id));
CREATE TABLE user_restriction (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE, exercise_id VARCHAR(60) REFERENCES wod_exercise(id), pattern_id VARCHAR(40) REFERENCES movement_pattern(id), equipment_id VARCHAR(40) REFERENCES equipment(id), muscle_id VARCHAR(40) REFERENCES muscle_group(id), reason VARCHAR(250) NOT NULL, active BOOLEAN NOT NULL, CHECK ((CASE WHEN exercise_id IS NULL THEN 0 ELSE 1 END + CASE WHEN pattern_id IS NULL THEN 0 ELSE 1 END + CASE WHEN equipment_id IS NULL THEN 0 ELSE 1 END + CASE WHEN muscle_id IS NULL THEN 0 ELSE 1 END)=1));
CREATE INDEX restriction_user ON user_restriction(user_id);
CREATE TABLE wods (id UUID PRIMARY KEY, owner_id UUID NOT NULL REFERENCES athletes(id), title VARCHAR(100) NOT NULL, generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, type_id VARCHAR(20) NOT NULL REFERENCES wod_type(id), stimulus_id VARCHAR(30) NOT NULL REFERENCES wod_stimulus(id), level_id INT NOT NULL REFERENCES wod_level(id), duration_minutes INT NOT NULL, rounds INT NOT NULL, intensity INT NOT NULL, assessed_difficulty DOUBLE PRECISION NOT NULL, instructions VARCHAR(1000) NOT NULL, config_json TEXT NOT NULL, revision INT NOT NULL DEFAULT 1, frozen BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE history_exercise (wod_id UUID REFERENCES wods(id) ON DELETE CASCADE, position INT NOT NULL, exercise_id VARCHAR(60) REFERENCES wod_exercise(id), snapshot_json TEXT NOT NULL, PRIMARY KEY(wod_id,position));
CREATE TABLE user_wod (wod_id UUID REFERENCES wods(id) ON DELETE CASCADE, user_id UUID REFERENCES athletes(id) ON DELETE CASCADE, scheduled_on DATE NOT NULL, status VARCHAR(12) NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','completed','skipped')), completed_on DATE, duration_seconds INT, rounds_completed INT, extra_reps INT, effort INT, notes VARCHAR(2000) NOT NULL DEFAULT '', joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(wod_id,user_id), CHECK ((status='completed' AND completed_on IS NOT NULL) OR (status<>'completed' AND completed_on IS NULL)), CHECK(effort BETWEEN 1 AND 10), CHECK(duration_seconds BETWEEN 1 AND 86400), CHECK(rounds_completed BETWEEN 0 AND 1000), CHECK(extra_reps BETWEEN 0 AND 10000));
CREATE INDEX user_wod_schedule ON user_wod(user_id,scheduled_on);
CREATE INDEX user_wod_completion ON user_wod(user_id,completed_on);
INSERT INTO movement_pattern VALUES ('squat','Squat'),('hinge','Hip hinge'),('lunge','Lunge'),('push','Push'),('pull','Pull'),('core','Core / brace'),('locomotion','Locomotion'),('jump','Jump');
INSERT INTO movement_type VALUES ('cyclical','Cyclical'),('compound','Compound'),('isometric','Isometric');
INSERT INTO exercise_category VALUES ('gymnastics','Bodyweight / gymnastics'),('weightlifting','Weightlifting'),('conditioning','Conditioning');
INSERT INTO equipment VALUES ('dumbbells','Dumbbells'),('kettlebell','Kettlebell'),('barbell','Barbell + plates'),('pullup-bar','Pull-up bar'),('rings','Rings / suspension straps'),('box','Stable exercise box'),('rower','Rowing machine'),('bike','Stationary bike'),('rope','Jump rope');
INSERT INTO muscle_group VALUES ('quads','Quads'),('hamstrings','Hamstrings'),('glutes','Glutes'),('calves','Calves'),('chest','Chest'),('back','Back'),('shoulders','Shoulders'),('triceps','Triceps'),('biceps','Biceps'),('core','Core');
INSERT INTO exercise_family VALUES ('squat','Squat'),('hinge','Hinge'),('lunge','Lunge'),('horizontal-push','Horizontal-Push'),('vertical-push','Vertical-Push'),('horizontal-pull','Horizontal-Pull'),('vertical-pull','Vertical-Pull'),('brace','Brace'),('trunk-flexion','Trunk-Flexion'),('cardio','Cardio'),('burpee','Burpee'),('jump','Jump');
INSERT INTO wod_type VALUES ('AMRAP','AMRAP'),('EMOM','EMOM'),('FOR_TIME','For Time'),('CHIPPER','Chipper');
INSERT INTO wod_stimulus VALUES ('balanced','Balanced conditioning'),('engine','Aerobic engine'),('strength','Strength endurance');
INSERT INTO wod_template VALUES ('amrap-balanced','Amrap / balanced','balanced','AMRAP',3,8,20);
INSERT INTO wod_template VALUES ('amrap-engine','Amrap / engine','engine','AMRAP',3,8,20);
INSERT INTO wod_template VALUES ('amrap-strength','Amrap / strength','strength','AMRAP',3,8,20);
INSERT INTO wod_template VALUES ('emom-balanced','Emom / balanced','balanced','EMOM',3,8,20);
INSERT INTO wod_template VALUES ('emom-engine','Emom / engine','engine','EMOM',3,8,20);
INSERT INTO wod_template VALUES ('emom-strength','Emom / strength','strength','EMOM',3,8,20);
INSERT INTO wod_template VALUES ('for_time-balanced','For Time / balanced','balanced','FOR_TIME',3,8,20);
INSERT INTO wod_template VALUES ('for_time-engine','For Time / engine','engine','FOR_TIME',3,8,20);
INSERT INTO wod_template VALUES ('for_time-strength','For Time / strength','strength','FOR_TIME',3,8,20);
INSERT INTO wod_template VALUES ('chipper-balanced','Chipper / balanced','balanced','CHIPPER',3,8,20);
INSERT INTO wod_template VALUES ('chipper-engine','Chipper / engine','engine','CHIPPER',3,8,20);
INSERT INTO wod_template VALUES ('chipper-strength','Chipper / strength','strength','CHIPPER',3,8,20);
INSERT INTO wod_exercise VALUES ('air-squat','Air squat','squat','gymnastics','compound',1,'reps',3,'Controlled depth; feet stay planted.');
INSERT INTO exercise_pattern VALUES ('air-squat','squat');
INSERT INTO exercise_muscle VALUES ('air-squat','quads'),('air-squat','glutes'),('air-squat','core');
INSERT INTO exercise_level_config VALUES ('air-squat',1,10,0.0);
INSERT INTO exercise_level_config VALUES ('air-squat',2,11,0.0);
INSERT INTO exercise_level_config VALUES ('air-squat',3,12,0.0);
INSERT INTO exercise_level_config VALUES ('air-squat',4,14,0.0);
INSERT INTO exercise_level_config VALUES ('air-squat',5,15,0.0);
INSERT INTO exercise_level_config VALUES ('air-squat',6,16,0.0);
INSERT INTO wod_exercise VALUES ('goblet-squat','Goblet squat','squat','weightlifting','compound',2,'reps',3,'Total kettlebell weight held at chest.');
INSERT INTO exercise_equipment VALUES ('goblet-squat','kettlebell');
INSERT INTO exercise_pattern VALUES ('goblet-squat','squat');
INSERT INTO exercise_muscle VALUES ('goblet-squat','quads'),('goblet-squat','glutes'),('goblet-squat','core');
INSERT INTO exercise_level_config VALUES ('goblet-squat',1,8,8.0);
INSERT INTO exercise_level_config VALUES ('goblet-squat',2,9,10.0);
INSERT INTO exercise_level_config VALUES ('goblet-squat',3,10,12.0);
INSERT INTO exercise_level_config VALUES ('goblet-squat',4,11,14.0);
INSERT INTO exercise_level_config VALUES ('goblet-squat',5,12,16.0);
INSERT INTO exercise_level_config VALUES ('goblet-squat',6,13,18.0);
INSERT INTO wod_exercise VALUES ('front-squat','Barbell front squat','squat','weightlifting','compound',4,'reps',4,'Total barbell load; use a load you can control.');
INSERT INTO exercise_equipment VALUES ('front-squat','barbell');
INSERT INTO exercise_pattern VALUES ('front-squat','squat');
INSERT INTO exercise_muscle VALUES ('front-squat','quads'),('front-squat','glutes'),('front-squat','core'),('front-squat','shoulders');
INSERT INTO exercise_level_config VALUES ('front-squat',1,6,20.0);
INSERT INTO exercise_level_config VALUES ('front-squat',2,7,25.0);
INSERT INTO exercise_level_config VALUES ('front-squat',3,7,30.0);
INSERT INTO exercise_level_config VALUES ('front-squat',4,8,35.0);
INSERT INTO exercise_level_config VALUES ('front-squat',5,9,40.0);
INSERT INTO exercise_level_config VALUES ('front-squat',6,10,45.0);
INSERT INTO wod_exercise VALUES ('reverse-lunge','Reverse lunge','lunge','gymnastics','compound',1,'reps',3,'Alternating legs; reps are total across both legs.');
INSERT INTO exercise_pattern VALUES ('reverse-lunge','lunge');
INSERT INTO exercise_muscle VALUES ('reverse-lunge','quads'),('reverse-lunge','glutes'),('reverse-lunge','hamstrings');
INSERT INTO exercise_level_config VALUES ('reverse-lunge',1,12,0.0);
INSERT INTO exercise_level_config VALUES ('reverse-lunge',2,13,0.0);
INSERT INTO exercise_level_config VALUES ('reverse-lunge',3,15,0.0);
INSERT INTO exercise_level_config VALUES ('reverse-lunge',4,16,0.0);
INSERT INTO exercise_level_config VALUES ('reverse-lunge',5,18,0.0);
INSERT INTO exercise_level_config VALUES ('reverse-lunge',6,19,0.0);
INSERT INTO wod_exercise VALUES ('db-lunge','Dumbbell reverse lunge','lunge','weightlifting','compound',3,'reps',3,'Weight per dumbbell. Reps are total across both legs.');
INSERT INTO exercise_equipment VALUES ('db-lunge','dumbbells');
INSERT INTO exercise_pattern VALUES ('db-lunge','lunge');
INSERT INTO exercise_muscle VALUES ('db-lunge','quads'),('db-lunge','glutes'),('db-lunge','hamstrings');
INSERT INTO exercise_level_config VALUES ('db-lunge',1,10,5.0);
INSERT INTO exercise_level_config VALUES ('db-lunge',2,11,6.0);
INSERT INTO exercise_level_config VALUES ('db-lunge',3,12,7.5);
INSERT INTO exercise_level_config VALUES ('db-lunge',4,14,9.0);
INSERT INTO exercise_level_config VALUES ('db-lunge',5,15,10.0);
INSERT INTO exercise_level_config VALUES ('db-lunge',6,16,11.0);
INSERT INTO wod_exercise VALUES ('glute-bridge','Glute bridge','hinge','gymnastics','compound',1,'reps',3,'Pause at the top without overextending the back.');
INSERT INTO exercise_pattern VALUES ('glute-bridge','hinge');
INSERT INTO exercise_muscle VALUES ('glute-bridge','glutes'),('glute-bridge','hamstrings'),('glute-bridge','core');
INSERT INTO exercise_level_config VALUES ('glute-bridge',1,12,0.0);
INSERT INTO exercise_level_config VALUES ('glute-bridge',2,13,0.0);
INSERT INTO exercise_level_config VALUES ('glute-bridge',3,15,0.0);
INSERT INTO exercise_level_config VALUES ('glute-bridge',4,16,0.0);
INSERT INTO exercise_level_config VALUES ('glute-bridge',5,18,0.0);
INSERT INTO exercise_level_config VALUES ('glute-bridge',6,19,0.0);
INSERT INTO wod_exercise VALUES ('kb-deadlift','Kettlebell deadlift','hinge','weightlifting','compound',1,'reps',3,'Total kettlebell load; controlled hinge.');
INSERT INTO exercise_equipment VALUES ('kb-deadlift','kettlebell');
INSERT INTO exercise_pattern VALUES ('kb-deadlift','hinge');
INSERT INTO exercise_muscle VALUES ('kb-deadlift','hamstrings'),('kb-deadlift','glutes'),('kb-deadlift','back');
INSERT INTO exercise_level_config VALUES ('kb-deadlift',1,10,8.0);
INSERT INTO exercise_level_config VALUES ('kb-deadlift',2,11,10.0);
INSERT INTO exercise_level_config VALUES ('kb-deadlift',3,12,12.0);
INSERT INTO exercise_level_config VALUES ('kb-deadlift',4,14,14.0);
INSERT INTO exercise_level_config VALUES ('kb-deadlift',5,15,16.0);
INSERT INTO exercise_level_config VALUES ('kb-deadlift',6,16,18.0);
INSERT INTO wod_exercise VALUES ('kb-swing','Russian kettlebell swing','hinge','weightlifting','compound',3,'reps',2,'Swing to chest height; total kettlebell load.');
INSERT INTO exercise_equipment VALUES ('kb-swing','kettlebell');
INSERT INTO exercise_pattern VALUES ('kb-swing','hinge');
INSERT INTO exercise_muscle VALUES ('kb-swing','hamstrings'),('kb-swing','glutes'),('kb-swing','core'),('kb-swing','shoulders');
INSERT INTO exercise_level_config VALUES ('kb-swing',1,10,8.0);
INSERT INTO exercise_level_config VALUES ('kb-swing',2,11,10.0);
INSERT INTO exercise_level_config VALUES ('kb-swing',3,12,12.0);
INSERT INTO exercise_level_config VALUES ('kb-swing',4,14,14.0);
INSERT INTO exercise_level_config VALUES ('kb-swing',5,15,16.0);
INSERT INTO exercise_level_config VALUES ('kb-swing',6,16,18.0);
INSERT INTO wod_exercise VALUES ('barbell-deadlift','Barbell deadlift','hinge','weightlifting','compound',3,'reps',4,'Total barbell load; reset between reps.');
INSERT INTO exercise_equipment VALUES ('barbell-deadlift','barbell');
INSERT INTO exercise_pattern VALUES ('barbell-deadlift','hinge');
INSERT INTO exercise_muscle VALUES ('barbell-deadlift','hamstrings'),('barbell-deadlift','glutes'),('barbell-deadlift','back');
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',1,6,20.0);
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',2,7,25.0);
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',3,7,30.0);
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',4,8,35.0);
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',5,9,40.0);
INSERT INTO exercise_level_config VALUES ('barbell-deadlift',6,10,45.0);
INSERT INTO wod_exercise VALUES ('wall-pushup','Wall push-up','horizontal-push','gymnastics','compound',1,'reps',3,'Stand at a wall; adjust foot distance for comfort.');
INSERT INTO exercise_pattern VALUES ('wall-pushup','push');
INSERT INTO exercise_muscle VALUES ('wall-pushup','chest'),('wall-pushup','triceps'),('wall-pushup','shoulders');
INSERT INTO exercise_level_config VALUES ('wall-pushup',1,8,0.0);
INSERT INTO exercise_level_config VALUES ('wall-pushup',2,9,0.0);
INSERT INTO exercise_level_config VALUES ('wall-pushup',3,10,0.0);
INSERT INTO exercise_level_config VALUES ('wall-pushup',4,11,0.0);
INSERT INTO exercise_level_config VALUES ('wall-pushup',5,12,0.0);
INSERT INTO exercise_level_config VALUES ('wall-pushup',6,13,0.0);
INSERT INTO wod_exercise VALUES ('knee-pushup','Knee push-up','horizontal-push','gymnastics','compound',1,'reps',3,'Keep a straight line from knees to shoulders.');
INSERT INTO exercise_pattern VALUES ('knee-pushup','push');
INSERT INTO exercise_muscle VALUES ('knee-pushup','chest'),('knee-pushup','triceps'),('knee-pushup','shoulders'),('knee-pushup','core');
INSERT INTO exercise_level_config VALUES ('knee-pushup',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('knee-pushup',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('knee-pushup',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('knee-pushup',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('knee-pushup',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('knee-pushup',6,10,0.0);
INSERT INTO wod_exercise VALUES ('pushup','Push-up','horizontal-push','gymnastics','compound',2,'reps',3,'Full controlled range; scale before form deteriorates.');
INSERT INTO exercise_pattern VALUES ('pushup','push');
INSERT INTO exercise_muscle VALUES ('pushup','chest'),('pushup','triceps'),('pushup','shoulders'),('pushup','core');
INSERT INTO exercise_level_config VALUES ('pushup',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('pushup',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('pushup',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('pushup',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('pushup',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('pushup',6,10,0.0);
INSERT INTO wod_exercise VALUES ('db-floor-press','Dumbbell floor press','horizontal-push','weightlifting','compound',2,'reps',3,'Weight per dumbbell; upper arms touch floor gently.');
INSERT INTO exercise_equipment VALUES ('db-floor-press','dumbbells');
INSERT INTO exercise_pattern VALUES ('db-floor-press','push');
INSERT INTO exercise_muscle VALUES ('db-floor-press','chest'),('db-floor-press','triceps'),('db-floor-press','shoulders');
INSERT INTO exercise_level_config VALUES ('db-floor-press',1,8,5.0);
INSERT INTO exercise_level_config VALUES ('db-floor-press',2,9,6.0);
INSERT INTO exercise_level_config VALUES ('db-floor-press',3,10,7.5);
INSERT INTO exercise_level_config VALUES ('db-floor-press',4,11,9.0);
INSERT INTO exercise_level_config VALUES ('db-floor-press',5,12,10.0);
INSERT INTO exercise_level_config VALUES ('db-floor-press',6,13,11.0);
INSERT INTO wod_exercise VALUES ('db-press','Dumbbell strict press','vertical-push','weightlifting','compound',2,'reps',3,'Weight per dumbbell; no leg drive.');
INSERT INTO exercise_equipment VALUES ('db-press','dumbbells');
INSERT INTO exercise_pattern VALUES ('db-press','push');
INSERT INTO exercise_muscle VALUES ('db-press','shoulders'),('db-press','triceps'),('db-press','core');
INSERT INTO exercise_level_config VALUES ('db-press',1,6,4.0);
INSERT INTO exercise_level_config VALUES ('db-press',2,7,5.0);
INSERT INTO exercise_level_config VALUES ('db-press',3,7,6.0);
INSERT INTO exercise_level_config VALUES ('db-press',4,8,7.0);
INSERT INTO exercise_level_config VALUES ('db-press',5,9,8.0);
INSERT INTO exercise_level_config VALUES ('db-press',6,10,9.0);
INSERT INTO wod_exercise VALUES ('pike-pushup','Pike push-up','vertical-push','gymnastics','compound',4,'reps',4,'Keep hips high; use controlled range.');
INSERT INTO exercise_pattern VALUES ('pike-pushup','push');
INSERT INTO exercise_muscle VALUES ('pike-pushup','shoulders'),('pike-pushup','triceps'),('pike-pushup','core');
INSERT INTO exercise_level_config VALUES ('pike-pushup',1,5,0.0);
INSERT INTO exercise_level_config VALUES ('pike-pushup',2,6,0.0);
INSERT INTO exercise_level_config VALUES ('pike-pushup',3,6,0.0);
INSERT INTO exercise_level_config VALUES ('pike-pushup',4,7,0.0);
INSERT INTO exercise_level_config VALUES ('pike-pushup',5,7,0.0);
INSERT INTO exercise_level_config VALUES ('pike-pushup',6,8,0.0);
INSERT INTO wod_exercise VALUES ('db-row','Bent-over dumbbell row','horizontal-pull','weightlifting','compound',1,'reps',3,'Weight per dumbbell; both arms move together.');
INSERT INTO exercise_equipment VALUES ('db-row','dumbbells');
INSERT INTO exercise_pattern VALUES ('db-row','pull'),('db-row','hinge');
INSERT INTO exercise_muscle VALUES ('db-row','back'),('db-row','biceps'),('db-row','hamstrings');
INSERT INTO exercise_level_config VALUES ('db-row',1,10,5.0);
INSERT INTO exercise_level_config VALUES ('db-row',2,11,6.0);
INSERT INTO exercise_level_config VALUES ('db-row',3,12,7.5);
INSERT INTO exercise_level_config VALUES ('db-row',4,14,9.0);
INSERT INTO exercise_level_config VALUES ('db-row',5,15,10.0);
INSERT INTO exercise_level_config VALUES ('db-row',6,16,11.0);
INSERT INTO wod_exercise VALUES ('ring-row','Ring row','horizontal-pull','gymnastics','compound',2,'reps',3,'Adjust body angle; more upright is easier.');
INSERT INTO exercise_equipment VALUES ('ring-row','rings');
INSERT INTO exercise_pattern VALUES ('ring-row','pull');
INSERT INTO exercise_muscle VALUES ('ring-row','back'),('ring-row','biceps'),('ring-row','core');
INSERT INTO exercise_level_config VALUES ('ring-row',1,8,0.0);
INSERT INTO exercise_level_config VALUES ('ring-row',2,9,0.0);
INSERT INTO exercise_level_config VALUES ('ring-row',3,10,0.0);
INSERT INTO exercise_level_config VALUES ('ring-row',4,11,0.0);
INSERT INTO exercise_level_config VALUES ('ring-row',5,12,0.0);
INSERT INTO exercise_level_config VALUES ('ring-row',6,13,0.0);
INSERT INTO wod_exercise VALUES ('scapular-pullup','Scapular pull-up','vertical-pull','gymnastics','compound',2,'reps',3,'Arms stay straight; controlled shoulder-blade movement.');
INSERT INTO exercise_equipment VALUES ('scapular-pullup','pullup-bar');
INSERT INTO exercise_pattern VALUES ('scapular-pullup','pull');
INSERT INTO exercise_muscle VALUES ('scapular-pullup','back'),('scapular-pullup','shoulders');
INSERT INTO exercise_level_config VALUES ('scapular-pullup',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('scapular-pullup',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('scapular-pullup',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('scapular-pullup',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('scapular-pullup',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('scapular-pullup',6,10,0.0);
INSERT INTO wod_exercise VALUES ('strict-pullup','Strict pull-up','vertical-pull','gymnastics','compound',4,'reps',4,'No kipping. Use a full controlled range.');
INSERT INTO exercise_equipment VALUES ('strict-pullup','pullup-bar');
INSERT INTO exercise_pattern VALUES ('strict-pullup','pull');
INSERT INTO exercise_muscle VALUES ('strict-pullup','back'),('strict-pullup','biceps'),('strict-pullup','core');
INSERT INTO exercise_level_config VALUES ('strict-pullup',1,4,0.0);
INSERT INTO exercise_level_config VALUES ('strict-pullup',2,4,0.0);
INSERT INTO exercise_level_config VALUES ('strict-pullup',3,5,0.0);
INSERT INTO exercise_level_config VALUES ('strict-pullup',4,5,0.0);
INSERT INTO exercise_level_config VALUES ('strict-pullup',5,6,0.0);
INSERT INTO exercise_level_config VALUES ('strict-pullup',6,6,0.0);
INSERT INTO wod_exercise VALUES ('dead-bug','Dead bug','brace','gymnastics','compound',1,'reps',3,'Alternate sides; reps are total.');
INSERT INTO exercise_pattern VALUES ('dead-bug','core');
INSERT INTO exercise_muscle VALUES ('dead-bug','core');
INSERT INTO exercise_level_config VALUES ('dead-bug',1,12,0.0);
INSERT INTO exercise_level_config VALUES ('dead-bug',2,13,0.0);
INSERT INTO exercise_level_config VALUES ('dead-bug',3,15,0.0);
INSERT INTO exercise_level_config VALUES ('dead-bug',4,16,0.0);
INSERT INTO exercise_level_config VALUES ('dead-bug',5,18,0.0);
INSERT INTO exercise_level_config VALUES ('dead-bug',6,19,0.0);
INSERT INTO wod_exercise VALUES ('plank','Forearm plank','brace','gymnastics','isometric',1,'seconds',1,'Stop the hold when trunk position cannot be maintained.');
INSERT INTO exercise_pattern VALUES ('plank','core');
INSERT INTO exercise_muscle VALUES ('plank','core'),('plank','shoulders');
INSERT INTO exercise_level_config VALUES ('plank',1,20,0.0);
INSERT INTO exercise_level_config VALUES ('plank',2,22,0.0);
INSERT INTO exercise_level_config VALUES ('plank',3,25,0.0);
INSERT INTO exercise_level_config VALUES ('plank',4,27,0.0);
INSERT INTO exercise_level_config VALUES ('plank',5,30,0.0);
INSERT INTO exercise_level_config VALUES ('plank',6,32,0.0);
INSERT INTO wod_exercise VALUES ('hollow-hold','Hollow-body hold','brace','gymnastics','isometric',3,'seconds',1,'Bend knees to reduce difficulty.');
INSERT INTO exercise_pattern VALUES ('hollow-hold','core');
INSERT INTO exercise_muscle VALUES ('hollow-hold','core');
INSERT INTO exercise_level_config VALUES ('hollow-hold',1,15,0.0);
INSERT INTO exercise_level_config VALUES ('hollow-hold',2,17,0.0);
INSERT INTO exercise_level_config VALUES ('hollow-hold',3,19,0.0);
INSERT INTO exercise_level_config VALUES ('hollow-hold',4,20,0.0);
INSERT INTO exercise_level_config VALUES ('hollow-hold',5,22,0.0);
INSERT INTO exercise_level_config VALUES ('hollow-hold',6,24,0.0);
INSERT INTO wod_exercise VALUES ('situp','Sit-up','trunk-flexion','gymnastics','compound',2,'reps',3,'Controlled reps; use a comfortable range.');
INSERT INTO exercise_pattern VALUES ('situp','core');
INSERT INTO exercise_muscle VALUES ('situp','core');
INSERT INTO exercise_level_config VALUES ('situp',1,8,0.0);
INSERT INTO exercise_level_config VALUES ('situp',2,9,0.0);
INSERT INTO exercise_level_config VALUES ('situp',3,10,0.0);
INSERT INTO exercise_level_config VALUES ('situp',4,11,0.0);
INSERT INTO exercise_level_config VALUES ('situp',5,12,0.0);
INSERT INTO exercise_level_config VALUES ('situp',6,13,0.0);
INSERT INTO wod_exercise VALUES ('march','Brisk march','cardio','conditioning','cyclical',1,'seconds',1,'March in place at a conversational pace.');
INSERT INTO exercise_pattern VALUES ('march','locomotion');
INSERT INTO exercise_muscle VALUES ('march','quads'),('march','glutes'),('march','calves');
INSERT INTO exercise_level_config VALUES ('march',1,30,0.0);
INSERT INTO exercise_level_config VALUES ('march',2,34,0.0);
INSERT INTO exercise_level_config VALUES ('march',3,37,0.0);
INSERT INTO exercise_level_config VALUES ('march',4,41,0.0);
INSERT INTO exercise_level_config VALUES ('march',5,44,0.0);
INSERT INTO exercise_level_config VALUES ('march',6,48,0.0);
INSERT INTO wod_exercise VALUES ('run','Run','cardio','conditioning','cyclical',2,'meters',0.4,'Distance in meters; use a clear route.');
INSERT INTO exercise_pattern VALUES ('run','locomotion');
INSERT INTO exercise_muscle VALUES ('run','quads'),('run','hamstrings'),('run','glutes'),('run','calves');
INSERT INTO exercise_level_config VALUES ('run',1,100,0.0);
INSERT INTO exercise_level_config VALUES ('run',2,112,0.0);
INSERT INTO exercise_level_config VALUES ('run',3,124,0.0);
INSERT INTO exercise_level_config VALUES ('run',4,136,0.0);
INSERT INTO exercise_level_config VALUES ('run',5,148,0.0);
INSERT INTO exercise_level_config VALUES ('run',6,160,0.0);
INSERT INTO wod_exercise VALUES ('row','Row','cardio','conditioning','cyclical',1,'calories',4,'Calories shown on the rower; consistent technique.');
INSERT INTO exercise_equipment VALUES ('row','rower');
INSERT INTO exercise_pattern VALUES ('row','pull'),('row','hinge');
INSERT INTO exercise_muscle VALUES ('row','back'),('row','quads'),('row','hamstrings'),('row','glutes');
INSERT INTO exercise_level_config VALUES ('row',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('row',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('row',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('row',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('row',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('row',6,10,0.0);
INSERT INTO wod_exercise VALUES ('bike','Bike','cardio','conditioning','cyclical',1,'calories',4,'Calories shown on the bike; stay seated if needed.');
INSERT INTO exercise_equipment VALUES ('bike','bike');
INSERT INTO exercise_pattern VALUES ('bike','locomotion');
INSERT INTO exercise_muscle VALUES ('bike','quads'),('bike','glutes'),('bike','calves');
INSERT INTO exercise_level_config VALUES ('bike',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('bike',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('bike',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('bike',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('bike',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('bike',6,10,0.0);
INSERT INTO wod_exercise VALUES ('single-under','Single-under','jump','conditioning','cyclical',2,'reps',1,'One rope pass per jump.');
INSERT INTO exercise_equipment VALUES ('single-under','rope');
INSERT INTO exercise_pattern VALUES ('single-under','jump');
INSERT INTO exercise_muscle VALUES ('single-under','calves'),('single-under','quads'),('single-under','shoulders');
INSERT INTO exercise_level_config VALUES ('single-under',1,20,0.0);
INSERT INTO exercise_level_config VALUES ('single-under',2,22,0.0);
INSERT INTO exercise_level_config VALUES ('single-under',3,25,0.0);
INSERT INTO exercise_level_config VALUES ('single-under',4,27,0.0);
INSERT INTO exercise_level_config VALUES ('single-under',5,30,0.0);
INSERT INTO exercise_level_config VALUES ('single-under',6,32,0.0);
INSERT INTO wod_exercise VALUES ('double-under','Double-under','jump','conditioning','cyclical',5,'reps',1,'Two rope passes per jump; skill-dependent.');
INSERT INTO exercise_equipment VALUES ('double-under','rope');
INSERT INTO exercise_pattern VALUES ('double-under','jump');
INSERT INTO exercise_muscle VALUES ('double-under','calves'),('double-under','quads'),('double-under','shoulders');
INSERT INTO exercise_level_config VALUES ('double-under',1,15,0.0);
INSERT INTO exercise_level_config VALUES ('double-under',2,17,0.0);
INSERT INTO exercise_level_config VALUES ('double-under',3,19,0.0);
INSERT INTO exercise_level_config VALUES ('double-under',4,20,0.0);
INSERT INTO exercise_level_config VALUES ('double-under',5,22,0.0);
INSERT INTO exercise_level_config VALUES ('double-under',6,24,0.0);
INSERT INTO wod_exercise VALUES ('stepup','Box step-up','jump','gymnastics','compound',1,'reps',4,'Stable box at a comfortable height; alternating total reps.');
INSERT INTO exercise_equipment VALUES ('stepup','box');
INSERT INTO exercise_pattern VALUES ('stepup','lunge');
INSERT INTO exercise_muscle VALUES ('stepup','quads'),('stepup','glutes'),('stepup','calves');
INSERT INTO exercise_level_config VALUES ('stepup',1,8,0.0);
INSERT INTO exercise_level_config VALUES ('stepup',2,9,0.0);
INSERT INTO exercise_level_config VALUES ('stepup',3,10,0.0);
INSERT INTO exercise_level_config VALUES ('stepup',4,11,0.0);
INSERT INTO exercise_level_config VALUES ('stepup',5,12,0.0);
INSERT INTO exercise_level_config VALUES ('stepup',6,13,0.0);
INSERT INTO wod_exercise VALUES ('box-jump','Box jump, step down','jump','gymnastics','compound',4,'reps',4,'Land softly and step down; use a manageable height.');
INSERT INTO exercise_equipment VALUES ('box-jump','box');
INSERT INTO exercise_pattern VALUES ('box-jump','jump'),('box-jump','squat');
INSERT INTO exercise_muscle VALUES ('box-jump','quads'),('box-jump','glutes'),('box-jump','calves');
INSERT INTO exercise_level_config VALUES ('box-jump',1,6,0.0);
INSERT INTO exercise_level_config VALUES ('box-jump',2,7,0.0);
INSERT INTO exercise_level_config VALUES ('box-jump',3,7,0.0);
INSERT INTO exercise_level_config VALUES ('box-jump',4,8,0.0);
INSERT INTO exercise_level_config VALUES ('box-jump',5,9,0.0);
INSERT INTO exercise_level_config VALUES ('box-jump',6,10,0.0);
INSERT INTO wod_exercise VALUES ('stepback-burpee','Step-back burpee, no push-up','burpee','gymnastics','compound',2,'reps',6,'Step back to plank, step in and stand. No jump.');
INSERT INTO exercise_pattern VALUES ('stepback-burpee','push'),('stepback-burpee','hinge'),('stepback-burpee','core');
INSERT INTO exercise_muscle VALUES ('stepback-burpee','chest'),('stepback-burpee','shoulders'),('stepback-burpee','core'),('stepback-burpee','quads'),('stepback-burpee','glutes');
INSERT INTO exercise_level_config VALUES ('stepback-burpee',1,5,0.0);
INSERT INTO exercise_level_config VALUES ('stepback-burpee',2,6,0.0);
INSERT INTO exercise_level_config VALUES ('stepback-burpee',3,6,0.0);
INSERT INTO exercise_level_config VALUES ('stepback-burpee',4,7,0.0);
INSERT INTO exercise_level_config VALUES ('stepback-burpee',5,7,0.0);
INSERT INTO exercise_level_config VALUES ('stepback-burpee',6,8,0.0);
INSERT INTO wod_exercise VALUES ('burpee','Burpee','burpee','gymnastics','compound',3,'reps',6,'Chest to floor, stand and make a small jump.');
INSERT INTO exercise_pattern VALUES ('burpee','push'),('burpee','jump'),('burpee','squat');
INSERT INTO exercise_muscle VALUES ('burpee','chest'),('burpee','triceps'),('burpee','shoulders'),('burpee','core'),('burpee','quads'),('burpee','glutes');
INSERT INTO exercise_level_config VALUES ('burpee',1,5,0.0);
INSERT INTO exercise_level_config VALUES ('burpee',2,6,0.0);
INSERT INTO exercise_level_config VALUES ('burpee',3,6,0.0);
INSERT INTO exercise_level_config VALUES ('burpee',4,7,0.0);
INSERT INTO exercise_level_config VALUES ('burpee',5,7,0.0);
INSERT INTO exercise_level_config VALUES ('burpee',6,8,0.0);
INSERT INTO wod_exercise VALUES ('db-thruster','Dumbbell thruster','squat','weightlifting','compound',4,'reps',4,'Weight per dumbbell; squat into an overhead press.');
INSERT INTO exercise_equipment VALUES ('db-thruster','dumbbells');
INSERT INTO exercise_pattern VALUES ('db-thruster','squat'),('db-thruster','push');
INSERT INTO exercise_muscle VALUES ('db-thruster','quads'),('db-thruster','glutes'),('db-thruster','shoulders'),('db-thruster','triceps'),('db-thruster','core');
INSERT INTO exercise_level_config VALUES ('db-thruster',1,6,4.0);
INSERT INTO exercise_level_config VALUES ('db-thruster',2,7,5.0);
INSERT INTO exercise_level_config VALUES ('db-thruster',3,7,6.0);
INSERT INTO exercise_level_config VALUES ('db-thruster',4,8,7.0);
INSERT INTO exercise_level_config VALUES ('db-thruster',5,9,8.0);
INSERT INTO exercise_level_config VALUES ('db-thruster',6,10,9.0);
